### ISSUE TITLE
twitchban.sh is using incompatible line endings

### ISSUE THREAD

**Issue by ghost** [therealnagia/twitchbanfromlist#6] opened 2021-09-03 18:17 UTC
When I first tried it, I got an error that said something along the lines of `bad interpreter No such file or directory`

I had to run `sed -i -e 's/\r$//' twitchban.sh` to fix it, this changes the Windows line endings to Unix line endings.

I can easily make a pull request for this, would you like the PR to be sent to the main branch or the beta branch? @therealnagia

**Comment by therealnagia** [comment] 2021-09-04 00:15
Oh so, I'm so sorry. I merged it after only looking at the code, I didn't check line returns. Please send to beta branch and I'll merge back into main tonight! Thank you for checking!

**Comment by ghost** [comment] 2021-09-04 22:26
It seems that the script in the beta branch is already working properly.

The script I attempted to run and got the error from is the one in the releases page.

You probably just need to publish another release.

**Comment by therealnagia** [comment] 2021-09-09 09:11
Apologies for the late update. Just pushed a new release. Let me know if it still has the issue?

**Comment by biosniper** [comment] 2021-09-10 22:13
I can confirm the issue is still present. Had to rectify this in my local copy. 
Looks like DOS line endings rather than linux/unix 

I've made a pull requested with my one that I've tested as working.. Fingers crossed?

**Comment by therealnagia** [comment] 2021-09-11 05:04
Thank you!!!

Should be fixed per #10

**Closed as completed by therealnagia** 2021-09-11 05:04 UTC
